### ISSUE TITLE
Integrated Marketing Campaign - Future Leaders of Open Source

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/marketing#18]
This is the parent issue, organizing the **action items**, **key dates**, and **execution** for recruiting future leaders for Bit Project. 

### Logistics
Launch Date: April 8th, 2020
Marketing Manager : @shreyagupta98 

### Objective
Identify and recruit key student organization leaders in student organizations around the country to be future leaders at Bit Project. 

### OKRs
**Results**
- Number of Leads Generated
- Number of New Applicants and Successful recruits

**Activity**
- Number of opportunities created
- Number of meetings held
- Number of personalized emails sent

### Target persona
Bryan Lee, President (Link Persona Here) 
Cynthia Chang, Director of Marketing (Link Persona Here) 

### Key Timeline Dates
**April 12, 2020**
- [x] Create Milestone
- [ ] Update IMC Parent Issue 
- [ ] Outline Plan to Generate Leads

- [ ] Write and Update Cold Emails
- [ ] Nuture Sequence Outline Plan
- [ ] Social Media Plan Written (With the Social Team) 
- [ ] Content Plan Written (WIth Content Team) 
- [ ] Set Up Webinar to Attarct Future Student Org Leaders
