### ISSUE TITLE
Integrated Marketing Campaign - Accessible Data Science Education

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/marketing#22]
This is the parent issue, organizing the **action items**, **key dates**, and **execution** for Publicizing our Data Science Education Initiatives. 

### Logistics
Launch Date: April 13, 2020
Marketing Manager : [Marketing Manager Github Username]

### OKRs
**Results**

**Activity**

### Target persona
Developer Advocate @ Data Science Promoted Companies 
Graduate Student Groups in Data Science [Davis + Communities]
Undergraduate Statistics/Economics departments across the country

### Key Timeline Dates
**April 12, 2020**
- [ ] Create Milestone
- [ ] Update IMC Parent Issue 
- [ ] Outline Plan to Generate Leads

- [ ] Write and Update Cold Emails
- [ ] Nuture Sequence Outline Plan
- [ ] Social Media Plan Written (With the Social Team) 
- [ ] Content Plan Written (WIth Content Team) 
- [ ] Set Up Webinar to Attarct Future Student Org Leaders
