### ISSUE TITLE
[IMC] Stage 1: Awareness

### ISSUE THREAD

**Issue by shreythecray** [bitprj/marketing#28]
## Objective:
Collect contacts on instutions all over the United States in various deparments (Math, Statistics, Economics, Computational Social Sciences) to enact future marketing action plans. 
## Action Plan (Tentative) 
- Send Email (Customized Based on Department) On How Interactive Curriculum could be integrated into their classes. 
 - Hold a Webinar with Industry Partner ( Twitter ) to advertise how we partner with industry to bring hands-on practical education to UC Davis Social Science students.
- Create Template for Professors to follow to recruit their own students to join Bit Project

## Persona:
@shreyagupta98 
- [ ] Social Sciences Professor
- [ ] Economics Professor
- [ ] Comunications Professor
- [ ] Math Professor
- [ ] Graduate Student TA
## Airtable
**[Marketing University Outreach - Twitter Webinar [May]](https://airtable.com/tblRN2fngeYXUlGGp/viwsMjkCDCTJNoUDE?blocks=hide)**

## West Coast
- [x] #29 @eden-bouskila 

## East Coast
- [ ] #30 @bkim1478

## Mid West
- [x] #31 @montsui 

## South
- [x] #32 @iriszhong7 

# Design
Collaborate with Content Marketing on Custom Illustrations and Graphics on Content Development

# Content Writing
- [ ] Case Study about Twitter x Bit Project regarding using real world datasets to teach social sciences. 

**one page briefs on how** 
- [ ] Social Sciences Professor
- [ ] Economics Professor
- [ ] Comunications Professor
- [ ] Math Professor
- [ ] Graduate Student TA

can use Hands-on CS labs in their curriculum

 - [ ] Edit Twitter Hands-on Activities from DevRel in Blog Format

**Comment by shreythecray** [comment]
> so we want professors to
1. Talk about the impact of COVID 19 on teaching (Cause thats the hot button issue)
2. Talk about how they use real life data/data science and coding in their teaching to bolster the theory
<sub>[View in Slack](https://bitdarlene.slack.com/archives/G011GU59H6K/p1587274166007600)</sub>
